version: "3"

services:
  function:
    build: .
    ports:
      - 9000:8080
    environment:
      - POWERTOOLS_LOG_LEVEL=DEBUG
      - POWERTOOLS_SERVICE_NAME=WeasyPrint-Test
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_RELEASE=0.0
      - SENTRY_ENVIRONMENT=local
    volumes:
      - ./volume:/volume
  gateway:
    image: public.ecr.aws/eagletmt/aws-lambda-rie-gateway
    ports:
      - 8080:8080
    environment:
      - TARGET_URL=http://function:8080
