[tool.black]
line-length = 80

[tool.isort]
profile = "black"
include_trailing_comma = true
line_length = 80
multi_line_output = 3
combine_as_imports = true

[tool.mypy]
ignore_missing_imports = true
